# Mini PyECOD Production Test Configuration
# Generated by setup_production_testing.py

# Test Data Files
DOMAIN_LENGTHS_FILE = "test_data/domain_lengths.csv"
PROTEIN_LENGTHS_FILE = "test_data/protein_lengths.csv"
DOMAIN_DEFINITIONS_FILE = "test_data/domain_definitions.csv"
ECOD_CLASSIFICATIONS_FILE = "test_data/ecod_classifications.csv"

# Production Test Proteins
PRODUCTION_TEST_PROTEINS = ['8ovp_A']

# ECOD Source Files (for reference)
RANGE_CACHE_FILE = "/data/ecod/database_versions/v291/ecod.develop291.range_cache.txt"
DOMAINS_FILE = "/data/ecod/database_versions/v291/ecod.develop291.domains.txt"

# Test Thresholds
MIN_ACCEPTABLE_QUALITY_SCORE = -0.2    # Allow up to 20% degradation from current
PREFERRED_QUALITY_SCORE = 0.1          # Prefer 10% improvement
MIN_ACCEPTABLE_RATE = 0.8               # 80% of tests must be acceptable

# Performance Benchmarks
MAX_PROCESSING_TIME_8OVP_A = 60.0       # seconds
TARGET_PERFORMANCE_IMPROVEMENT = 0.2    # 20% faster than current

# Coverage Requirements
MIN_COVERAGE_8OVP_A = 0.85              # 85% sequence coverage
MIN_DOMAIN_COUNT_8OVP_A = 2             # At least 2 domains
EXPECTED_DOMAIN_COUNT_8OVP_A = 3        # Preferably 3 domains

# ECOD Classification Requirements
MIN_ECOD_ACCURACY = 0.7                 # 70% classification accuracy
TARGET_ECOD_ACCURACY = 0.9              # 90% classification accuracy
